/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

CREATE TABLE IF NOT EXISTS `ff_ceo` (
  `Identifier` varchar(255) COLLATE armscii8_bin DEFAULT NULL,
  `IsCEO` varchar(255) COLLATE armscii8_bin DEFAULT NULL,
  `OrganizationName` varchar(255) COLLATE armscii8_bin DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=armscii8 COLLATE=armscii8_bin;

/*!40000 ALTER TABLE `ff_ceo` DISABLE KEYS */;
/*!40000 ALTER TABLE `ff_ceo` ENABLE KEYS */;

CREATE TABLE IF NOT EXISTS `ff_inventory` (
  `Identifier` varchar(255) COLLATE armscii8_bin DEFAULT NULL,
  `Cola` int(11) DEFAULT NULL,
  `Bread` int(11) DEFAULT NULL,
  `Water` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=armscii8 COLLATE=armscii8_bin;

/*!40000 ALTER TABLE `ff_inventory` DISABLE KEYS */;
/*!40000 ALTER TABLE `ff_inventory` ENABLE KEYS */;

CREATE TABLE IF NOT EXISTS `ff_jobs` (
  `Name` varchar(255) COLLATE armscii8_bin DEFAULT NULL,
  `Salary` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=armscii8 COLLATE=armscii8_bin;

/*!40000 ALTER TABLE `ff_jobs` DISABLE KEYS */;
/*!40000 ALTER TABLE `ff_jobs` ENABLE KEYS */;

CREATE TABLE IF NOT EXISTS `ff_users` (
  `Identifier` varchar(255) COLLATE armscii8_bin DEFAULT NULL,
  `Nickname` varchar(255) COLLATE armscii8_bin DEFAULT NULL,
  `Name` varchar(255) COLLATE armscii8_bin DEFAULT NULL,
  `Cash` float DEFAULT NULL,
  `Bank` float DEFAULT NULL,
  `Admin` varchar(255) COLLATE armscii8_bin DEFAULT NULL,
  `Job` varchar(255) COLLATE armscii8_bin DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=armscii8 COLLATE=armscii8_bin;

/*!40000 ALTER TABLE `ff_users` DISABLE KEYS */;
/*!40000 ALTER TABLE `ff_users` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
